#\u914d\u7f6e\u6570\u636e\u6e90
spring:
  devtools:
    restart:
      enabled: false
    
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      first:             
        url: jdbc:mysql://jdbc.asdzy.com:9906/YaoDian?characterEncoding=utf8&zeroDateTimeBehavior=round&useSSL=false&allowMultiQueries=true
        username: sdzy_root   
        password: asdzy_DB_123                
      second:
        driverClassName: com.mysql.jdbc.Driver	    
        url: jdbc:mysql://121.201.54.57:9935/YaoDianTest?characterEncoding=utf8&zeroDateTimeBehavior=round&useSSL=false
        username: root
        password: asdzy_DB_123
      three:  
        driverClassName: com.mysql.jdbc.Driver	   
        url: jdbc:mysql://jdbc.asdzy.com:9906/membercenter?characterEncoding=utf8&zeroDateTimeBehavior=round&useSSL=false
        username: sdzy_root   
        password: asdzy_DB_123
      four:  
        driverClassName: com.mysql.jdbc.Driver	   
        url: jdbc:mysql://119.29.6.138:9090/YaoDianServiceCenter?characterEncoding=utf8&zeroDateTimeBehavior=round&useSSL=false
        username: sdzy   
        password: asdzy
      
        
        
      maxActive: 50
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
     
  mvc:
    view:
      prefix : /views/
      suffix : .jsp

#\u67e5\u770b\u7cfb\u7edf\u73af\u5883    /actuator
management:
  address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "*"
        
mybatis-plus:
  global-config:
    #\u4e3b\u952e\u7c7b\u578b  0:"\u6570\u636e\u5e93ID\u81ea\u589e", 1:"\u7528\u6237\u8f93\u5165ID",2:"\u5168\u5c40\u552f\u4e00ID (\u6570\u5b57\u7c7b\u578b\u552f\u4e00ID)", 3:"\u5168\u5c40\u552f\u4e00ID UUID";
    id-type: 5
    #\u5b57\u6bb5\u7b56\u7565 0:"\u5ffd\u7565\u5224\u65ad",1:"\u975e NULL \u5224\u65ad"),2:"\u975e\u7a7a\u5224\u65ad"
    field-strategy: 2
    #\u9a7c\u5cf0\u4e0b\u5212\u7ebf\u8f6c\u6362
    db-column-underline: false
    #\u5237\u65b0mapper \u8c03\u8bd5\u795e\u5668
    refresh-mapper: true
    #\u6570\u636e\u5e93\u5927\u5199\u4e0b\u5212\u7ebf\u8f6c\u6362
    #capital-mode: true
    #\u903b\u8f91\u5220\u9664\u914d\u7f6e\uff08\u4e0b\u97623\u4e2a\u914d\u7f6e\uff09
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL \u89e3\u6790\u7f13\u5b58\uff0c\u5f00\u542f\u540e\u591a\u79df\u6237 @SqlParser \u6ce8\u89e3\u751f\u6548
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false



